github.com:
    users:
        Lexnaid:
            oauth_token: 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
    git_protocol: https
    user: Lexnaid
    oauth_token: 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
